// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Yanbal.Examen.Infra.Data.MainContext.Context;

namespace Yanbal.Examen.Infra.Data.MainContext.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Yanbal.Examen.Domain.MainContext.Aggregates.ClienteAgg.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<DateTime?>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Apellidos = "Alcantara",
                            Correo = "carlos@dominio.com",
                            FechaRegistro = new DateTime(2021, 1, 27, 13, 17, 22, 481, DateTimeKind.Local).AddTicks(8304),
                            Nombres = "Carlos"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Apellidos = "Reyes",
                            Correo = "luis@dominio.com",
                            FechaRegistro = new DateTime(2021, 1, 27, 13, 17, 22, 482, DateTimeKind.Local).AddTicks(9827),
                            Nombres = "Luis"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Apellidos = "Pinillos",
                            Correo = "marcos1@dominio.com",
                            FechaRegistro = new DateTime(2021, 1, 27, 13, 17, 22, 482, DateTimeKind.Local).AddTicks(9867),
                            Nombres = "Marcos"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Apellidos = "Buis",
                            Correo = "marcos2@dominio.com",
                            FechaRegistro = new DateTime(2021, 1, 27, 13, 17, 22, 482, DateTimeKind.Local).AddTicks(9870),
                            Nombres = "Marcos"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Apellidos = "Coronel",
                            Correo = "alberto@dominio.com",
                            FechaRegistro = new DateTime(2021, 1, 27, 13, 17, 22, 482, DateTimeKind.Local).AddTicks(9872),
                            Nombres = "Alberto"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
